### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by bastianccm** [yo1000/keycloak-update-email-with-verification#1]
Hi @yo1000

nice work! Do you mind adding a license if this is okay to be used by others?

Thank you very much

**Comment by yo1000** [comment]
@bastianccm san

Thank you for contacting me. I forgot to add the license, so I've applied the MIT license. Please feel free to use it.
Also, it seems that an official PullRequest with similar functionality was recently created, so please take a look at that as well.

https://github.com/keycloak/keycloak/pull/7943

**Comment by bastianccm** [comment]
@yo1000 thank you so much!

I've seen that issue, however according to the Keycloak issue it seems to be planned to go into the Keycloak 15 release, so I am super happy you implemented it as a regular extension.
