### ISSUE TITLE
keycloak 17 support

### ISSUE THREAD

**Issue by bohze** [yo1000/keycloak-update-email-with-verification#2]
Hi @yo1000

will this work with keycloak 17?

**Comment by yo1000** [comment]
@bohze san
Thanks for the question.

I had not tried it yet, so I tested it.
The main change that affected this module appeared to be only a correction to the abstract class name that was Typo.

`org.keycloak.authentication.actiontoken.AbstractActionTokenHander` -> `org.keycloak.authentication.actiontoken.AbstractActionTokenHandler`

I have created a tag for Keycloak 17 for ease of reference.
https://github.com/yo1000/keycloak-update-email-with-verification/tree/v17.0.1

**Comment by bohze** [comment]
@yo1000 thank you!

works perfectly fine
